'use client'
import Head from 'next/head'
import Layout from '../components/Layout'
import { ThemeProvider } from '@mui/material/styles'
import { RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ToastContainer } from 'react-toastify'
import theme from '../utils/theme'
import { config } from '../utils/wagmi'
import { WagmiProvider } from 'wagmi'
import '@rainbow-me/rainbowkit/styles.css'
import '../styles/globals.css'

import 'react-toastify/dist/ReactToastify.css'

const client = new QueryClient()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <Head>
        <title>KK Stack</title>
        <meta name="description" content="Generated by rainbowkit" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <body>
        <ThemeProvider theme={theme}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitProvider>
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
              />
              <Layout>{children}</Layout>
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
